### PR TITLE
Added media part on exchanges section

### PR DESCRIPTION
**Pull request by seeatend**

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
thanks but please fix two issues:
- static/images/Logo_black.png the name should reflect whose logo it is
- please do not convert theme.css to windows newlines

**Comment by tonyofbyteball** [comment]
also please make Media its own section, not part of the Exchanges

**Comment by tonyofbyteball** [comment]
thanks for the fixes.
regarding auto language selection, not sure it works as users expect, did you check how it behaves on non-index pages? is it possible to choose any other language?

**Comment by seeatend** [comment]
Hello Tony,
Regarding the language localization, it works depending on the user's browser language setting.
For example, if user set the language of browser as French, index.html.fr will be displayed automatically instead of index.html.
If it is not the result that you expect, please explain me about the requirements in detail.
Thank you.

**Comment by tonyofbyteball** [comment]
could you please exclude the language thing from this PR into a separate one, we need the media section and can't spend more time discussing the stuff that is unrelated.

**Comment by seeatend** [comment]
Sorry for the delay.
I've removed the language task from this PR.

**Pull request merged**
