### PR TITLE
Update theme.css

### PR DESCRIPTION
**Pull request by MTraveller**
Added align-items and fixes #features content, after adding align-items: center;

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
could you elaborate what it fixes.  I'm concerned that changing .row class can potentially change a lot of other things (I didn't check).

**Comment by MTraveller** [comment]
I've tested it in the browser. It just vertical center aligns content, nothing else, and the 2nd sets the features content as is right now because it slightly changes when the first comment gets added.

**Comment by MTraveller** [comment]
This puts everything in the middle of each section.

**Comment by MTraveller** [comment]
You can check it easily and quickly, by opening chrome, byteball.org, right click inspect, click sources tab => Static => css, click theme.css

now insert.

.row{align-items:center;}

and see.

**Comment by MTraveller** [comment]
Have you checked it yet?

**Comment by tonyofbyteball** [comment]
I tried it, this makes the tops of images and texts not aligned, not sure I like it.

**Comment by MTraveller** [comment]
Yes, they would be aligned from the middle of the row so that they are verticle centred. Which most websites go with these days.

**Comment by MTraveller** [comment]
exsample: https://www.decred.org/

**Pull request closed without merging**
